.gitignore
README.md
config.json
src/graphic/index.html

Include ai2html configuration
Closes #26

Include ai2html configuration

---

README.md
package.json

Changes yarn start to yarn dev for consistency

change `yarn start` to `yarn dev`

---

.gitignore

Ignore data files by default

---

package.json
src/graphic/js/graphic.js
src/index.html
src/js/index.js
yarn.lock

Adds a button that allows people to download the graphic as a PNG.
This works by listening for a button click. When the button is clicked, the Pym parent sends a message to the Pym child. The Pym child then generates the PNG. The Pym parent can't directly generate the PNG because `html-to-image` can't seem to find the correct styles from the parent.
N/A
See #8.
1. Clone and checkout to this branch.
2. Spin up your server.
3. Click the button.
4. Try resizing your iframe width.
5. Try adding some SVG content
```javascript
const data = new Map()
.set("A", 4)
.set("B", 2)
.set("C", 9)
.set("D", 5)
.set("E", 8);
const figure = d3.select("figure");
const width = figure.node().clientWidth;
const height = 300;
const margin = { left: 50, top: 20, right: 20, bottom: 20 };
const x = d3 …
```

Add button for client-side image download

---

src/graphic/js/graphic.js
src/js/index.js

Send width in screengrab listener

---

src/js/index.js

Destructure resizer observer entry

---

Makefile

Add glob to gh-pages build

---

package.json
yarn.lock

Adds auto typing for CSV imports

Bump parcel-transformer-csv

---

package.json
yarn.lock

Add postinstall script for sink

---

Makefile
README.md

Modify GitHub Pages deploy flow

---

Makefile
README.md
config.json
package.json
yarn.lock

Add AWS deployment config and instructions

---

README.md
src/graphic/css/main.scss

Add homepage styles

---

README.md
build.mjs
package.json
yarn.lock

Add environment variable to skip screenshots

---

README.md
package.json
yarn.lock

Bump `parcel-transformer-csv`

---

package.json
yarn.lock

Bump transformers

---

.parcelrc
README.md
package.json
yarn.lock

Upgrade parcel-transformer-dsv

---

src/css/base.scss
src/graphic/js/util/set-display.js
src/graphic/template/base.html
src/index.html

Add conditional rendering and hiding for options

---

README.md
src/css/base.scss
src/css/colors.scss
src/css/fonts.scss
src/graphic/css/graphic.scss
src/graphic/css/main.scss

Replace sass variables with CSS variables

---

.vscode/settings.json

Disable automatic linting

---

package.json
src/graphic/js/util/download-image.js
yarn.lock

Remove dependency for PNG download

---

src/index.html

Check for filename in entries

---

src/graphic/js/util/download-image.js

Encode SVG string with base64

---

src/index.html

Use absolute path for index imports

---

.eslintrc.cjs

Simplify eslint config

---

package.json
yarn.lock

Upgrade DSV plugin

---

README.md
config.json
package.json
src/graphic/js/graphic.js
yarn.lock

Add bore as default dependency

---

package.json
src/graphic/js/util/download-image.js
yarn.lock

Fix fonts in PNG screenshot

---

README.md
build.mjs

Turn screenshot process off by default
